name: Build Complete Export

on:
  workflow_dispatch:
    inputs:
      include_grants:
        description: 'Include grant templates?'
        required: false
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build full export
        run: |
          mkdir -p out
          cp -r . out/
          rm -rf out/.git out/.github
          cd out && zip -r ../AIUZ_Complete_Export.zip .
          cd .. && echo "ZIP created"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AIUZ_Complete_Export
          path: AIUZ_Complete_Export.zip
