name: Build ZIP Only

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create ZIP
        run: |
          zip -r AIUZ_Complete_Export.zip .
      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: AIUZ_Complete_Export
          path: AIUZ_Complete_Export.zip
